# -*- coding: utf-8 -*-
"""Metadatos de columnas: tipo, formato, visibilidad y orden."""

# (nombre, dataType, formatString, oculta, sortByColumn, descripcion)
C = lambda n, t, f=None, oc=False, sb=None, d=None: (n, t, f, oc, sb, d)

FECHA = "dd/mm/yyyy"
ENTERO = "#,0"
DECIMAL = "#,0.00"

TABLAS = {
    "Fact_Guias": [
        C("GuiaID", "string", None, False, None, "Clave de la guía: planilla-pedido-factura."),
        C("Planilla", "int64", "0"),
        C("Pedido", "int64", "0"),
        C("Factura", "int64", "0"),
        C("Cliente", "string", None, False, None, "Nombre del cliente tal como viene en el despacho."),
        C("ClienteKey", "string", None, True, None, "Nombre normalizado; une la guía con el maestro de clientes."),
        C("Cliente en Maestro", "boolean", None, False, None, "Falso si el cliente no existe en Dim_Clientes."),
        C("Vendedor", "string", None, False, None, "Vendedor asignado según el maestro de clientes."),
        C("Ciudad", "string", None, False, None, "Ciudad de la guía; si falta, la del maestro; si no, SIN CIUDAD."),
        C("Origen Ciudad", "string", None, False, None, "De dónde salió la ciudad: guía, maestro o sin dato."),
        C("Ruta", "string", None, False, None, "Ruta de cumplidos; si falta, la de despachos; si no, SIN RUTA."),
        C("Transportadora", "string"),
        C("Transportador", "string", None, False, None, "Conductor."),
        C("Placa", "string"),
        C("Peso KG", "double", DECIMAL),
        C("Fecha Despacho", "dateTime", FECHA),
        C("Plazo Días", "int64", "0", False, None, "Días pactados para la entrega."),
        C("Fecha Límite", "dateTime", FECHA),
        C("Días Transcurridos", "int64", "0"),
        C("Días Mora Origen", "int64", "0", False, None, "Mora calculada en el archivo de Excel."),
        C("Semáforo Origen", "string", None, False, None, "Semáforo del archivo, congelado a la fecha en que se generó."),
        C("Estado Cumplido", "string", None, False, None, "Sin diligenciar en el archivo actual."),
        C("Fecha Recibido", "dateTime", FECHA, False, None, "Sin diligenciar en el archivo actual."),
        C("Responsable", "string", None, False, None, "Sin diligenciar en el archivo actual."),
        C("Observaciones", "string"),
    ],
    "Dim_Clientes": [
        C("ClienteKey", "string", None, True),
        C("Código SN", "string"),
        C("Nombre SN", "string"),
        C("Ciudad", "string"),
        C("Dirección", "string"),
        C("Calle", "string"),
        C("Barrio", "string"),
        C("Teléfono", "string"),
        C("Correo", "string"),
        C("Lista de Precios", "string"),
        C("Vendedor", "string"),
    ],
    "Dim_Productos": [
        C("Código Producto", "string"),
        C("Descripción Producto", "string"),
        C("Línea", "string"),
        C("Descripción Línea", "string"),
        C("Grupo", "string"),
        C("Descripción Grupo", "string"),
        C("Peso KG", "double", DECIMAL),
        C("Unidad Empaque", "string"),
        C("Estado Peso", "string"),
        C("Referencia", "string"),
    ],
    "Dim_Calendario": [
        C("Fecha", "dateTime", FECHA),
        C("Año", "int64", "0"),
        C("Trimestre", "int64", "0"),
        C("Trimestre Nombre", "string", None, False, "Trimestre"),
        C("MesNum", "int64", "0", True),
        C("Mes", "string", None, False, "MesNum"),
        C("Año-Mes", "string", None, False, "Año-Mes Orden"),
        C("Año-Mes Orden", "int64", "0", True),
        C("Semana", "int64", "0"),
        C("DiaSemNum", "int64", "0", True),
        C("DiaSemana", "string", None, False, "DiaSemNum"),
        C("Es Fin de Semana", "boolean"),
    ],
    "Dim_Transportadora": [
        C("Transportadora", "string"),
        C("Tipo Transportadora", "string", None, False, None, "Flota propia, tercero o persona natural. Supuesto editable en la consulta."),
    ],
    "Dim_Ruta": [
        C("Ruta", "string"),
        C("Zona", "string", None, False, None, "Bogotá y sabana, nacional o sin clasificar."),
    ],
    "Fact_Devoluciones": [
        C("Consecutivo", "int64", "0"),
        C("Fecha Registro", "dateTime", FECHA),
        C("Planilla", "int64", "0"),
        C("Pedido", "int64", "0"),
        C("Factura", "int64", "0"),
        C("Cliente", "string"),
        C("ClienteKey", "string", None, True),
        C("Código SN", "string"),
        C("Ciudad", "string"),
        C("Vendedor", "string"),
        C("Ruta", "string"),
        C("Transportadora", "string"),
        C("Transportador", "string"),
        C("Placa", "string"),
        C("Fecha Despacho", "dateTime", FECHA),
        C("Código Producto", "string"),
        C("Descripción Producto", "string"),
        C("Unidad Empaque", "string"),
        C("Peso Unitario KG", "double", DECIMAL),
        C("Cantidad Devuelta", "double", DECIMAL),
        C("Peso Devuelto KG", "double", DECIMAL),
        C("Valor Unitario", "double", '"$"#,0.00'),
        C("Valor Devolución", "double", '"$"#,0.00'),
        C("Motivo Devolución", "string"),
        C("Estado", "string"),
        C("Fecha Recepción Bodega", "dateTime", FECHA),
        C("Nota Crédito", "string"),
        C("Fecha Nota Crédito", "dateTime", FECHA),
        C("Días de Gestión", "int64", "0"),
        C("Responsable", "string"),
        C("Observaciones", "string"),
    ],
    "_Medidas": [
        C("Grupo", "string", None, True),
    ],
}

# (nombre, tablaOrigen, columnaOrigen, tablaDestino, columnaDestino, activa)
RELACIONES = [
    ("rel_guias_calendario", "Fact_Guias", "Fecha Despacho", "Dim_Calendario", "Fecha", True),
    ("rel_guias_clientes", "Fact_Guias", "ClienteKey", "Dim_Clientes", "ClienteKey", True),
    ("rel_guias_transportadora", "Fact_Guias", "Transportadora", "Dim_Transportadora", "Transportadora", True),
    ("rel_guias_ruta", "Fact_Guias", "Ruta", "Dim_Ruta", "Ruta", True),
    ("rel_devol_calendario", "Fact_Devoluciones", "Fecha Registro", "Dim_Calendario", "Fecha", True),
    ("rel_devol_clientes", "Fact_Devoluciones", "ClienteKey", "Dim_Clientes", "ClienteKey", True),
    ("rel_devol_productos", "Fact_Devoluciones", "Código Producto", "Dim_Productos", "Código Producto", True),
]
